pack_directory = 'C:\Users\zocke\Documents\GitHub\Recources\'

output_file_path = 'C:\Users\zocke\Documents\GitHub\Recources'
recompress_compressed_files = true
zip_compression_iterations = 30
validate_pack_metadata_file = true
zip_spec_conformance_level = 'high'